kind: Deployment
apiVersion: apps/v1
metadata:
  name: baatchit-app
  namespace: chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: baatchit-app
        image: guravarchies/baatchit-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: firebase-secrets
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
