apiVersion: v1
kind: Secret
metadata:
  name: firebase-secrets
  namespace: chat-app
type: Opaque
data:
  REACT_APP_FIREBASE_API_KEY: QUl6YVN5Q0xkYVNKRGExTHVCSnV3dVhYZEc5Yi1oZzYxM1ZteTNF
  REACT_APP_FIREBASE_AUTH_DOMAIN: Y2hhdC1hcHAtNzJiNzUuZmlyZWJhc2VhcHAuY29t
  REACT_APP_FIREBASE_PROJECT_ID: Y2hhdC1hcHAtNzJiNzU=
  REACT_APP_FIREBASE_STORAGE_BUCKET: Y2hhdC1hcHAtNzJiNzUuZmlyZWJhc2VzdG9yYWdlLmFwcA==
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: NjMxNzg0NTE4NTI0
  REACT_APP_FIREBASE_APP_ID: MToxNjMxNzg0NTE4NTI0OndlYjpiMjMwZmNmYTE1MGI1N2MzMmEyYWY5
  REACT_APP_FIREBASE_MEASUREMENT_ID: Ry1NTjQ3R0taN1BN