kind: Service
apiVersion: v1
metadata:
  name: baatchit-app-svc
  namespace: chat-app
spec:
  selector:
    app: chat-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer