kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-role
  namespace: chat-app
rules:
- apiGroups: ["", "apps", "batch", "extensions", "autoscaling", "rbac.authorization.k8s.io", "policy"]
  resources:
    - "pods"
    - "secrets"
    - "services"
    - "deployments"
    - "replicasets"
    - "jobs"
    - "cronjobs"
    - "roles"
    - "rolebindings"
    - "endpoints"
    - "statefulsets"
    - "daemonsets"
    - "serviceaccounts"
    - "replicationcontrollers" 
    - "horizontalpodautoscalers" 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
